name: scc-hypervisor-collector version tagging

on:
  pull_request:
    types:
      - closed

jobs:
  bumpversion_if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Install package dependencies
      run: |
        #sudo apt-get update
        sudo apt-get install bumpversion

    - name: Checkout repo to workspace (full clone)
      uses: actions/checkout@v3
      with:
        #persist-credentials: false
        fetch-depth: '0'

    - name: Determine if version already bumped
      id: check_if_bumped
      run: |
        echo Check changes vs ${{ github.ref }}
        if git diff ${{ github.ref }} -- src/scc_hypervisor_collector/__init__.py | grep -sq "^[+]__version__"; then
          bumped=true
        else
          bumped=false
        fi
        echo "bumped=${bumped}" >> ${GITHUB_OUTPUT}

    - name: Configure git
      run: |
        git config --local user.name 'Version Bumping Bot'
        git config --local user.email ''
        #git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Bump patch if version isn't already being bumped
      if: steps.check_if_bumped.outputs.bumped == "false"
      run: |
        bumpversion patch
        git push

    - name: Create tag for bumped version
      run: |
        tag_prefix="f"
        prev_version=$(git describe --tags --abbrev=0 | tr -d "${tag_prefix}")
        new_version=$(grep -e "^__version__[[:space:]]*=[[:space:]]*" src/scc_hypervisor_collector/__init__.py | cut -d= -f2 | tr -d "[:space:]'")
        git tag -m "Bump version: ${prev_version} → ${new_version}" ${tag_prefix}${new_version}
        git push --tags

